# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29cbe722cd5b63ea1af326f66fab3f766ce25b014cd7764f1bf7ef7ff622bdc360754f943b92a2f34a7064025b216f72c8ac6d4fe8321fdb4b6c13de0b2f7cdc

test:
  secret_key_base: 70a761ef6772a7c721739e020b4c8fdb237edbd64fc71e3a7c40f9a7748b523f5b845e7ed6b241be520231f7169817324915972285621c97317e83c1ab421d72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
